build: false

environment:
    matrix:
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_SH: "CMAKE_SH-NOTFOUND"
          CMAKE_GENERATOR: "MinGW Makefiles"
          MINGW_HOME: "C:\\MinGW\\bin"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_SH: "CMAKE_SH-NOTFOUND"
          CMAKE_GENERATOR: "MinGW Makefiles"
          MINGW_HOME: "C:\\mingw-w64\\x86_64-6.3.0-posix-seh-rt_v5-rev1\\mingw64\\bin"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_SH: "CMAKE_SH-NOTFOUND"
          CMAKE_GENERATOR: "MinGW Makefiles"
          MINGW_HOME: "C:\\mingw-w64\\x86_64-7.2.0-posix-seh-rt_v5-rev1\\mingw64\\bin"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_SH: "CMAKE_SH-NOTFOUND"
          CMAKE_GENERATOR: "MinGW Makefiles"
          MINGW_HOME: "C:\\mingw-w64\\x86_64-7.3.0-posix-seh-rt_v5-rev0\\mingw64\\bin"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_SH: "CMAKE_SH-NOTFOUND"
          CMAKE_GENERATOR: "MinGW Makefiles"
          MINGW_HOME: "C:\\mingw-w64\\x86_64-8.1.0-posix-seh-rt_v6-rev0\\mingw64\\bin"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_GENERATOR: "Ninja"
          CC: "C:\\Program Files\\LLVM\\bin\\clang-cl.exe"
          VCVARS: "C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\vcvarsall.bat"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_GENERATOR: "Visual Studio 12 2013"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_GENERATOR: "Visual Studio 12 2013 Win64"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_GENERATOR: "Visual Studio 14 2015"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
          CMAKE_GENERATOR: "Visual Studio 14 2015 Win64"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CMAKE_GENERATOR: "Visual Studio 15 2017"
        - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
          CMAKE_GENERATOR: "Visual Studio 15 2017 Win64"

install:
    - mkdir C:\ninja
    - appveyor DownloadFile https://github.com/ninja-build/ninja/releases/download/v1.9.0/ninja-win.zip -FileName ninja.zip
    - 7z x ninja.zip -oC:\ninja > nul
    - set PATH=C:\ninja;%PATH%

test_script:
    - python build.py
